print("Area of a trapezoid")
questionHeight = int(input("Enter the height of the trapezoid: "))
questionLength = int(input("Enter the length of the bottom base: "))
questionTop = int(input("Enter the length of the top base: "))
Answer = (0.5*(questionLength + questionTop)*questionHeight)
answer = str(Answer)
print("The are is: " + answer)
